import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import {
    Box,
    Typography,
    Grid,
    Card,
    CardContent,
    CardActions,
    CardHeader,
    Button,
    List,
    ListItem,
    ListItemText,
    Dialog,
    DialogTitle,
    DialogContent,
    DialogActions,
    IconButton,
    TextField,
    InputAdornment,
    Snackbar,
    Alert,
    FormControl,
    FormLabel,
    RadioGroup,
    FormControlLabel,
    Radio,
    Tabs,
    Tab,
    CircularProgress
} from '@mui/material';
import {
    Search as SearchIcon,
    Clear as ClearIcon,
    AddCircle as AddCircleIcon,
    Delete as DeleteIcon,
    Favorite as FavoriteIcon,
    AutoFixHigh as GenerateIcon,
    SmartToy as AIIcon
} from '@mui/icons-material';
import { mockRecipes } from '../mockData';
import { useApp } from '../context/AppContext';

const Recipes = () => {
    const { recipes, toggleFavorite } = useApp();
    const [searchText, setSearchText] = useState('');
    const [selectedRecipe, setSelectedRecipe] = useState(null);
    const [dialogOpen, setDialogOpen] = useState(false);
    const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
    const [generateDialogOpen, setGenerateDialogOpen] = useState(false);
    const [notification, setNotification] = useState({ open: false, message: '', severity: 'success' });
    const [displayRecipes, setDisplayRecipes] = useState([]);
    const [recipeType, setRecipeType] = useState('available');
    const [generateTab, setGenerateTab] = useState(0);
    const [aiPrompt, setAiPrompt] = useState('');
    const [isGenerating, setIsGenerating] = useState(false);

    useEffect(() => {
        // Initialize with mock data if no recipes in context
        if (!recipes || recipes.length === 0) {
            const recipesWithFav = mockRecipes.map(recipe => ({
                ...recipe,
                is_fav: false
            }));
            setDisplayRecipes(recipesWithFav);
        } else {
            setDisplayRecipes(recipes);
        }
    }, [recipes]);

    const showNotification = (message, severity = 'success') => {
        setNotification({ open: true, message, severity });
    };

    const handleCloseNotification = () => {
        setNotification({ ...notification, open: false });
    };

    const handleViewRecipeDetails = (recipe) => {
        setSelectedRecipe(recipe);
        setDialogOpen(true);
    };

    const handleDeleteRecipe = () => {
        if (!selectedRecipe) return;
        // In a real app, this would make an API call
        const updatedRecipes = displayRecipes.filter(r => r._id !== selectedRecipe._id);
        setDisplayRecipes(updatedRecipes);
        showNotification('Recipe deleted successfully', 'success');
        setDeleteDialogOpen(false);
        setSelectedRecipe(null);
    };

    const handleToggleFavorite = (recipeId) => {
        const updatedRecipes = displayRecipes.map(recipe => 
            recipe._id === recipeId 
                ? { ...recipe, is_fav: !recipe.is_fav }
                : recipe
        );
        setDisplayRecipes(updatedRecipes);
        toggleFavorite(recipeId);
    };

    const handleGenerateRecipe = () => {
        if (generateTab === 0) {
            // Original generation logic
            const newRecipe = {
                _id: Date.now().toString(),
                name: `Generated ${recipeType} Recipe`,
                description: `A delicious recipe generated based on ${recipeType} ingredients`,
                ingredients: ['Ingredient 1', 'Ingredient 2', 'Ingredient 3'],
                instructions: '1. Step one\n2. Step two\n3. Step three',
                is_fav: false
            };
            setDisplayRecipes([...displayRecipes, newRecipe]);
            setGenerateDialogOpen(false);
            showNotification('Recipe generated successfully!', 'success');
        } else {
            // AI-based generation
            if (!aiPrompt.trim()) {
                showNotification('Please enter a description for your recipe', 'error');
                return;
            }
            setIsGenerating(true);
            
            // Simulate AI generation with a timeout
            setTimeout(() => {
                const newRecipe = {
                    _id: Date.now().toString(),
                    name: `AI Generated Recipe: ${aiPrompt.split(' ').slice(0, 3).join(' ')}`,
                    description: `A recipe generated by AI based on your request: "${aiPrompt}"`,
                    ingredients: [
                        'Ingredient 1',
                        'Ingredient 2',
                        'Ingredient 3',
                        'Ingredient 4'
                    ],
                    instructions: `1. First step based on ${aiPrompt}\n2. Second step\n3. Final step`,
                    is_fav: false
                };
                setDisplayRecipes([...displayRecipes, newRecipe]);
                setGenerateDialogOpen(false);
                setAiPrompt('');
                setIsGenerating(false);
                showNotification('AI Recipe generated successfully!', 'success');
            }, 2000);
        }
    };

    const filteredRecipes = displayRecipes.filter(recipe =>
        recipe && recipe.name && recipe.name.toLowerCase().includes(searchText.toLowerCase())
    );

    return (
        <Box>
            <Box display="flex" justifyContent="space-between" alignItems="center" mb={4}>
                <Typography variant="h4" fontWeight="bold">Recipes</Typography>
                <Button
                    variant="contained"
                    startIcon={<GenerateIcon />}
                    onClick={() => setGenerateDialogOpen(true)}
                >
                    Generate Recipe
                </Button>
            </Box>

            <Box mb={4}>
                <TextField
                    fullWidth
                    placeholder="Search recipes..."
                    value={searchText}
                    onChange={(e) => setSearchText(e.target.value)}
                    InputProps={{
                        startAdornment: (
                            <InputAdornment position="start">
                                <SearchIcon />
                            </InputAdornment>
                        ),
                        endAdornment: searchText && (
                            <InputAdornment position="end">
                                <IconButton size="small" onClick={() => setSearchText('')}>
                                    <ClearIcon />
                                </IconButton>
                            </InputAdornment>
                        )
                    }}
                />
            </Box>

            {filteredRecipes.length > 0 ? (
                <Grid container spacing={3}>
                    {filteredRecipes.map((recipe) => (
                        <Grid item xs={12} sm={6} md={4} key={recipe._id}>
                            <Card sx={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
                                <CardHeader
                                    title={recipe.name}
                                    action={
                                        <IconButton onClick={() => handleToggleFavorite(recipe._id)}>
                                            <FavoriteIcon color={recipe.is_fav ? "primary" : "action"} />
                                        </IconButton>
                                    }
                                />
                                <CardContent sx={{ flexGrow: 1 }}>
                                    <Typography variant="body2" color="text.secondary" paragraph>
                                        {recipe.description}
                                    </Typography>
                                    <Typography variant="subtitle2" gutterBottom>
                                        Ingredients:
                                    </Typography>
                                    <Typography variant="body2" color="text.secondary" paragraph>
                                        {recipe.ingredients.join(', ')}
                                    </Typography>
                                </CardContent>
                                <CardActions>
                                    <Button
                                        size="small"
                                        onClick={() => handleViewRecipeDetails(recipe)}
                                    >
                                        View Details
                                    </Button>
                                    <IconButton
                                        size="small"
                                        color="error"
                                        onClick={() => {
                                            setSelectedRecipe(recipe);
                                            setDeleteDialogOpen(true);
                                        }}
                                    >
                                        <DeleteIcon />
                                    </IconButton>
                                </CardActions>
                            </Card>
                        </Grid>
                    ))}
                </Grid>
            ) : (
                <Box textAlign="center" py={4}>
                    <Typography variant="h6" color="text.secondary">
                        No recipes found
                    </Typography>
                </Box>
            )}

            {/* Recipe Details Dialog */}
            <Dialog open={dialogOpen} onClose={() => setDialogOpen(false)} maxWidth="md" fullWidth>
                {selectedRecipe && (
                    <>
                        <DialogTitle>
                            <Box display="flex" justifyContent="space-between" alignItems="center">
                                <Typography variant="h6">{selectedRecipe.name}</Typography>
                                <IconButton onClick={() => handleToggleFavorite(selectedRecipe._id)}>
                                    <FavoriteIcon color={selectedRecipe.is_fav ? "primary" : "action"} />
                                </IconButton>
                            </Box>
                        </DialogTitle>
                        <DialogContent dividers>
                            <Typography variant="body1" paragraph>
                                {selectedRecipe.description}
                            </Typography>
                            <Typography variant="subtitle1" gutterBottom>
                                Ingredients:
                            </Typography>
                            <List dense>
                                {selectedRecipe.ingredients.map((ingredient, index) => (
                                    <ListItem key={index}>
                                        <ListItemText primary={ingredient} />
                                    </ListItem>
                                ))}
                            </List>
                            <Typography variant="subtitle1" gutterBottom>
                                Instructions:
                            </Typography>
                            <Typography variant="body1" sx={{ whiteSpace: 'pre-line' }}>
                                {selectedRecipe.instructions}
                            </Typography>
                        </DialogContent>
                        <DialogActions>
                            <Button onClick={() => setDialogOpen(false)}>Close</Button>
                        </DialogActions>
                    </>
                )}
            </Dialog>

            {/* Delete Confirmation Dialog */}
            <Dialog open={deleteDialogOpen} onClose={() => setDeleteDialogOpen(false)}>
                <DialogTitle>Delete Recipe</DialogTitle>
                <DialogContent>
                    <Typography>
                        Are you sure you want to delete "{selectedRecipe?.name}"?
                    </Typography>
                </DialogContent>
                <DialogActions>
                    <Button onClick={() => setDeleteDialogOpen(false)}>Cancel</Button>
                    <Button onClick={handleDeleteRecipe} color="error" variant="contained">
                        Delete
                    </Button>
                </DialogActions>
            </Dialog>

            {/* Generate Recipe Dialog */}
            <Dialog 
                open={generateDialogOpen} 
                onClose={() => {
                    setGenerateDialogOpen(false);
                    setAiPrompt('');
                    setIsGenerating(false);
                }}
                maxWidth="sm"
                fullWidth
            >
                <DialogTitle>Generate New Recipe</DialogTitle>
                <DialogContent>
                    <Tabs 
                        value={generateTab} 
                        onChange={(e, newValue) => setGenerateTab(newValue)}
                        sx={{ mb: 2 }}
                    >
                        <Tab label="Quick Generate" />
                        <Tab label="AI Generate" />
                    </Tabs>

                    {generateTab === 0 ? (
                        <FormControl component="fieldset" sx={{ mt: 2 }}>
                            <FormLabel component="legend">Recipe Type</FormLabel>
                            <RadioGroup
                                value={recipeType}
                                onChange={(e) => setRecipeType(e.target.value)}
                            >
                                <FormControlLabel 
                                    value="available" 
                                    control={<Radio />} 
                                    label="Use Available Ingredients" 
                                />
                                <FormControlLabel 
                                    value="expiring" 
                                    control={<Radio />} 
                                    label="Use Expiring Ingredients" 
                                />
                                <FormControlLabel 
                                    value="random" 
                                    control={<Radio />} 
                                    label="Generate Random Recipe" 
                                />
                            </RadioGroup>
                        </FormControl>
                    ) : (
                        <Box sx={{ mt: 2 }}>
                            <Typography variant="subtitle1" gutterBottom>
                                Describe the recipe you want to create
                            </Typography>
                            <TextField
                                fullWidth
                                multiline
                                rows={4}
                                placeholder="Example: A healthy vegetarian pasta dish with mushrooms and spinach, low in calories but high in protein..."
                                value={aiPrompt}
                                onChange={(e) => setAiPrompt(e.target.value)}
                                disabled={isGenerating}
                            />
                            <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
                                Be as specific as possible about ingredients, dietary restrictions, cooking time, or any other preferences.
                            </Typography>
                        </Box>
                    )}
                </DialogContent>
                <DialogActions>
                    <Button 
                        onClick={() => {
                            setGenerateDialogOpen(false);
                            setAiPrompt('');
                            setIsGenerating(false);
                        }}
                    >
                        Cancel
                    </Button>
                    <Button 
                        onClick={handleGenerateRecipe} 
                        variant="contained" 
                        color="primary"
                        disabled={isGenerating || (generateTab === 1 && !aiPrompt.trim())}
                        startIcon={isGenerating ? <CircularProgress size={20} color="inherit" /> : <AIIcon />}
                    >
                        {isGenerating ? 'Generating...' : 'Generate'}
                    </Button>
                </DialogActions>
            </Dialog>

            {/* Notification Snackbar */}
            <Snackbar
                open={notification.open}
                autoHideDuration={6000}
                onClose={handleCloseNotification}
                anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }}
            >
                <Alert onClose={handleCloseNotification} severity={notification.severity}>
                    {notification.message}
                </Alert>
            </Snackbar>
        </Box>
    );
};

export default Recipes;
